# Generated by Django 3.2 on 2024-10-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_alter_assignment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
    ]
