# Generated by Django 3.2 on 2024-10-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_remove_assignment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='marks',
            field=models.IntegerField(default=5),
        ),
    ]
