# Generated by Django 3.2 on 2024-10-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20241026_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
