# Generated by Django 3.2 on 2024-10-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_submission_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='course',
        ),
    ]
